# Site settings
title: 小木水的博客
SEOTitle: 小木水的博客 | MY Blog
header-img: img/bg.jpg
email: yi.chu317@gmail.com
description: "Academic and Life."
keyword: "MY Blog, 小木水的博客, 生活随笔, 摄影, 影评, 剧评"
url: "http://yic317.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://yic317.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "认清生活的真相后依然热爱生活"
sidebar-avatar: /img/Profile.JPG      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
zhihu_username:
github_username:    yic317
facebook_username:  Yi Chu
jianshu_username:




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 0bfb9215a4c537ca29dd                            #生成的clientID
  clientSecret: 3c4b1c27d27098b23315b2ac7ccec2051a58690a    #生成的clientSecret
  repo: yic317.github.io    #仓库名称
  owner: yic317    #github用户名
  admin: yic317
  distractionFreeMode: true #是否启用类似FB的阴影遮罩



# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id:

# Google Analytics
ga_track_id: 'UA-140773884-1'            # Format: UA-xxxxxx-xx
ga_domain: auto           # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
